### ISSUE TITLE
With python 3.8, delimiters values is lost

### ISSUE THREAD

**Issue by ochurlaud** [Mic92/python-mpd2#135]
I was trying to use this code: 

https://github.com/jplitza/mpd-snapcast-sync

and I got this backtrace:
```
Traceback (most recent call last):
  File "./main.py", line 132, in <module>
    argh.dispatch_command(main)
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 306, in dispatch_command
    dispatch(parser, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "./main.py", line 127, in main
    loop.run_until_complete(syncer.setup(snapcast_server, mpd_server))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./main.py", line 30, in setup
    await mpd_taskTraceback (most recent call last):
  File "./main.py", line 132, in <module>
    argh.dispatch_command(main)
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 306, in dispatch_command
    dispatch(parser, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "./main.py", line 127, in main
    loop.run_until_complete(syncer.setup(snapcast_server, mpd_server))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./main.py", line 30, in setup
    await mpd_task
  File "./main.py", line 107, in setup_mpd
    async for output in self.mpd.outputs():
  File "/usr/lib/python3.8/site-packages/mpd/asyncio.py", line 335, in __anext__
    if key in delimiters:
UnboundLocalError: local variable 'delimiters' referenced before assignment

  File "./main.py", line 107, in setup_mpd
    async for output in self.mpd.outputs():
  File "/usr/lib/python3.8/site-packages/mpd/asyncio.py", line 335, in __anext__
    if key in delimiters:
UnboundLocalError: local variable 'delimiters' referenced before assignment
```

Some analysis with `print()` calls in python-mpd2 showed that the `delimiters`  list is lost within the `async` call. My guess is that it's a reference loss (because it's created in a synchronous function dies very soon).

**Comment by ochurlaud** [comment]
OK it's the same issue as #117. When do you plan to release a fixed version for pip ?

**Comment by Mic92** [comment]
To be honest I don't really use or understand the asyncio backend. I only saw that newer versions of python3 throw deprecation warnings. So if someone could help to fix https://github.com/Mic92/python-mpd2/pull/134 I would keep the asyncio backend. Otherwise I might drop it in the next version.

**Comment by chrysn** [comment]
The commented-out code has probably not seen all the fixes that have accumulated in the manually-unrolled version over time. Just to ensure I'm testing the right thing: Which branch did your errors come from?

**Comment by Mic92** [comment]
2.0.0 was released.
