### ISSUE TITLE
Problem makefile()

### ISSUE THREAD

**Issue by entuccio** [Mic92/python-mpd2#163]
I got this error:

makefile() got an unexpected keyword argument 'newline'

What is my mistake?
Can I use this library in Python 2.7?

Thanks

**Comment by entuccio** [comment]
2243 ERROR    makefile() got an unexpected keyword argument 'newline'
Traceback (most recent call last):
  File "/Users/daniele/MyGoogleDrive/Alfred.alfredpreferences/workflows/user.workflow.1A3A1E44-FE8F-4F25-8EEE-E281EE9BCA96/lib/workflow/workflow.py", line 2236, in run
    func(self)
  File "./test.py", line 28, in main
    client.connect("localhost", 6600)  # connect to localhost:6600
  File "/Users/daniele/MyGoogleDrive/Alfred.alfredpreferences/workflows/user.workflow.1A3A1E44-FE8F-4F25-8EEE-E281EE9BCA96/mpd/base.py", line 797, in connect
    self._rbfile = self._sock.makefile("rb", newline="\n")
TypeError: makefile() got an unexpected keyword argument 'newline'

**Comment by Mic92** [comment]
python 2 support was dropped in https://github.com/Mic92/python-mpd2/releases/tag/v2.0.0

**Comment by entuccio** [comment]
Thank you. What is If I use a previous version? (like 1.0) ?

**Comment by Mic92** [comment]
yes. That would work, but we won't add new features or bug fixes to previous versions so you are on your own.

**Comment by entuccio** [comment]
Thank you dear. Great work.
